name: SDK with exp - C/C++ CI on Windows (vs2017)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: windows-2016
    name: Build

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Tools
      shell: cmd
      run: tools\setup-buildtools.cmd

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PULL_TOKEN: ${{ secrets.GIT_PULL_TOKEN }}
        SKIP_ARM_BUILD: 1
        SKIP_ARM64_BUILD: 1
      shell: cmd
      run: build-all.bat %CD%\Solutions\build.compact-exp.props

    - name: ListOutput
      shell: cmd
      run: tree %CD%\Solutions\out

    - name: Test
      shell: cmd
      run: test-all.cmd
